version: "3.9"

services:
  whisper-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisper-app
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - WHISPER_MODEL=medium
    ports:
      - "12345:12345"
      - "12346:12346"
      - "2222:22"   # mappa porta SSH
    volumes:
      - ./app:/app
    restart: unless-stopped
    command: ["/start.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
